Awesome books
hasnatali1947/Awesome-books pull request #1
Opened 2023-03-20 16:22 UTC by hasnatali1947

- added Html , CSS javaScript 
- added remove button

2023-03-20 17:55 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-20 17:55 UTC, abdulhamiid commented on index.js
> +}));
Good job so far! 👋, you are almost there 🏃‍♂️

According to the [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m1_plain_js_objects.md), we are supposed to create a collection that keeps a list of books. e.g
`const arr = []`
and then create a function to `add` a new book and to `remove`  a book from the collection, with the title and author. 

(hint: you can use an array of objects for that).
``` javaScript
arr = [{title: 'one', author: 'authorOne'}, {title: 'two', author: 'authorTwo'}]
```

Then, you can display all books saved in the array collection at the top part of the page. 💪

2023-03-20 17:55 UTC, abdulhamiid commented on index.js
> +author.value = dataSaved.author;
According to the [requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m1_plain_js_objects.md) data should be preserved in the browser's memory by using localStorage.

Please let's make sure that data is preserved in the browser's memory by using [localStorage](https://github.com/microverseinc/curriculum-html-css/blob/main/local_storage.md),

So that when the page refreshes or the user reloads the page manually, the data is preserved and displayed on the page after adding a book or removing a book.

2023-03-21 06:17 UTC, m05e5 approved these changes
**Hi @hasnatali1947 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge:shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights

✔️ Clean and well-organized code
✔️ no linters error

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-03-21 17:25 UTC, merged